# Generated by Django 4.0.3 on 2022-04-14 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_testuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
