# Generated by Django 4.0.3 on 2022-04-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_testuser_nickname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestUser',
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
