# Generated by Django 4.0.3 on 2022-04-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
